[package]
name = "animate-core"
version.workspace = true
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
readme = "../README.md"

[dependencies]
ratatui = { version = "0.30", optional = true }

[features]
default = []
global-clock = []
ratatui = ["dep:ratatui"]
